//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FelixWebsite.Core.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FelixResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FelixResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FelixWebsite.Shared.App_GlobalResources.FelixResources", typeof(FelixResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chassis nummer.
        /// </summary>
        public static string _2dehands_chassisnumber {
            get {
                return ResourceManager.GetString("_2dehands_chassisnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nummerplaat.
        /// </summary>
        public static string _2dehands_licenseplate {
            get {
                return ResourceManager.GetString("2dehands_licenseplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onderhoudsboekje.
        /// </summary>
        public static string _2dehands_manual {
            get {
                return ResourceManager.GetString("2dehands_manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volledig.
        /// </summary>
        public static string _2dehands_manual1 {
            get {
                return ResourceManager.GetString("2dehands_manual1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gedeeltelijk.
        /// </summary>
        public static string _2dehands_manual2 {
            get {
                return ResourceManager.GetString("2dehands_manual2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niet beschikbaar.
        /// </summary>
        public static string _2dehands_manual3 {
            get {
                return ResourceManager.GetString("2dehands_manual3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schade.
        /// </summary>
        public static string _2dehands_overview_photosDamage {
            get {
                return ResourceManager.GetString("2dehands_overview_photosDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documenten.
        /// </summary>
        public static string _2dehands_overview_photosDocuments {
            get {
                return ResourceManager.GetString("2dehands_overview_photosDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto&apos;s binnenkant.
        /// </summary>
        public static string _2dehands_overview_photosInside {
            get {
                return ResourceManager.GetString("2dehands_overview_photosInside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto overzicht wagen.
        /// </summary>
        public static string _2dehands_overview_photosOutside {
            get {
                return ResourceManager.GetString("2dehands_overview_photosOutside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schade.
        /// </summary>
        public static string _2dehands_overview_scheme_photosDamage {
            get {
                return ResourceManager.GetString("2dehands_overview_scheme_photosDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inschrijvingsbewijs voorzijde, inschrijvingsbewijs achterzijden, verzekeringsbewijs.
        /// </summary>
        public static string _2dehands_overview_scheme_photosDocs {
            get {
                return ResourceManager.GetString("2dehands_overview_scheme_photosDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto km-stand , Chassisnummer.
        /// </summary>
        public static string _2dehands_overview_scheme_photosInside {
            get {
                return ResourceManager.GetString("2dehands_overview_scheme_photosInside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto overzicht wagen.
        /// </summary>
        public static string _2dehands_overview_scheme_photosOutside {
            get {
                return ResourceManager.GetString("2dehands_overview_scheme_photosOutside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schade overzicht.
        /// </summary>
        public static string _2dehands_overview_scheme_title {
            get {
                return ResourceManager.GetString("_2dehands_overview_scheme_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto&apos;s.
        /// </summary>
        public static string _2dehands_progression_photos {
            get {
                return ResourceManager.GetString("2dehands_progression_photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uw verzoek tot overname werd succesvol aan ons bezorgd..
        /// </summary>
        public static string _2dehands_success_successMessage {
            get {
                return ResourceManager.GetString("2dehands_success_successMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uw verzoek tot schade aangifte werd succesvol aan ons bezorgd..
        /// </summary>
        public static string _2dehands_success_successMessage_damage {
            get {
                return ResourceManager.GetString("_2dehands_success_successMessage_damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uw verzoek wordt momenteel verwerkt, we sturen u spoedig een antwoord op volgend adres:.
        /// </summary>
        public static string _2dehands_success_successMessageContinue {
            get {
                return ResourceManager.GetString("2dehands_success_successMessageContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uw verzoek wordt momenteel verwerkt, we sturen u spoedig een antwoord op volgend adres:.
        /// </summary>
        public static string _2dehands_success_successMessageContinue_damage {
            get {
                return ResourceManager.GetString("_2dehands_success_successMessageContinue_damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bandenstatus.
        /// </summary>
        public static string _2dehands_tyrestate {
            get {
                return ResourceManager.GetString("2dehands_tyrestate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goed (&gt; 8mm).
        /// </summary>
        public static string _2dehands_tyrestate1 {
            get {
                return ResourceManager.GetString("2dehands_tyrestate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middelmatig.
        /// </summary>
        public static string _2dehands_tyrestate2 {
            get {
                return ResourceManager.GetString("2dehands_tyrestate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slecht (&lt; 4mm).
        /// </summary>
        public static string _2dehands_tyrestate3 {
            get {
                return ResourceManager.GetString("2dehands_tyrestate3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is een overname toegevoegd.
        /// </summary>
        public static string acquisition_mailFelix_heading {
            get {
                return ResourceManager.GetString("acquisition_mailFelix_heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is een schadeaangifte toegevoegd.
        /// </summary>
        public static string acquisition_mailFelix_heading_damages {
            get {
                return ResourceManager.GetString("acquisition_mailFelix_heading_damages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U vindt de overname op volgende link:.
        /// </summary>
        public static string acquisition_mailFelix_linkText {
            get {
                return ResourceManager.GetString("acquisition_mailFelix_linkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U vindt de schadeaangifte op volgende link:.
        /// </summary>
        public static string acquisition_mailFelix_linkText_damages {
            get {
                return ResourceManager.GetString("acquisition_mailFelix_linkText_damages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is iets misgegaan. Probeer nogmaals..
        /// </summary>
        public static string acquisition_notification_error {
            get {
                return ResourceManager.GetString("acquisition_notification_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schade binnenkant.
        /// </summary>
        public static string acquisition_overview_photosDamageInside {
            get {
                return ResourceManager.GetString("acquisition_overview_photosDamageInside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schade buitenkant.
        /// </summary>
        public static string acquisition_overview_photosDamageOutside {
            get {
                return ResourceManager.GetString("acquisition_overview_photosDamageOutside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Als u nog mogelijke opmerkingen heeft, kan u die hier oplijsten..
        /// </summary>
        public static string acquisition_overview_remarksText {
            get {
                return ResourceManager.GetString("acquisition_overview_remarksText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opmerkingen.
        /// </summary>
        public static string acquisition_overview_remarksTitle {
            get {
                return ResourceManager.GetString("acquisition_overview_remarksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze PDF bevat de foto&apos;s die u heeft doorgestuurd naar ons..
        /// </summary>
        public static string acquisition_pdf_header_text {
            get {
                return ResourceManager.GetString("acquisition_pdf_header_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inschrijvingbewijs achterkant.
        /// </summary>
        public static string acquisition_photos_backEnrollmentTitle {
            get {
                return ResourceManager.GetString("acquisition_photos_backEnrollmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achterzetels.
        /// </summary>
        public static string acquisition_photos_backseatsTitle {
            get {
                return ResourceManager.GetString("acquisition_photos_backseatsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chassisnummer.
        /// </summary>
        public static string acquisition_photos_chassisNumberTitle {
            get {
                return ResourceManager.GetString("acquisition_photos_chassisNumberTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schade.
        /// </summary>
        public static string acquisition_photos_damage {
            get {
                return ResourceManager.GetString("acquisition_photos_damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schade binnenkant.
        /// </summary>
        public static string acquisition_photos_damageInsideTitle {
            get {
                return ResourceManager.GetString("acquisition_photos_damageInsideTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schade buitenkant.
        /// </summary>
        public static string acquisition_photos_damageOutsideTitle {
            get {
                return ResourceManager.GetString("acquisition_photos_damageOutsideTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string acquisition_photos_dashTitle {
            get {
                return ResourceManager.GetString("acquisition_photos_dashTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documenten.
        /// </summary>
        public static string acquisition_photos_docs {
            get {
                return ResourceManager.GetString("acquisition_photos_docs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keuringsbewijs.
        /// </summary>
        public static string acquisition_photos_examinationProofTitle {
            get {
                return ResourceManager.GetString("acquisition_photos_examinationProofTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inschrijvingsbewijs voorkant.
        /// </summary>
        public static string acquisition_photos_frontEnrollmentTitle {
            get {
                return ResourceManager.GetString("acquisition_photos_frontEnrollmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voorzetels.
        /// </summary>
        public static string acquisition_photos_frontseatsTitle {
            get {
                return ResourceManager.GetString("acquisition_photos_frontseatsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binnenkant.
        /// </summary>
        public static string acquisition_photos_inside {
            get {
                return ResourceManager.GetString("acquisition_photos_inside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilometerstand.
        /// </summary>
        public static string acquisition_photos_kmTitle {
            get {
                return ResourceManager.GetString("acquisition_photos_kmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linksachter.
        /// </summary>
        public static string acquisition_photos_leftBackTitle {
            get {
                return ResourceManager.GetString("acquisition_photos_leftBackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linksvooraan.
        /// </summary>
        public static string acquisition_photos_leftFrontTitle {
            get {
                return ResourceManager.GetString("acquisition_photos_leftFrontTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buitenkant.
        /// </summary>
        public static string acquisition_photos_outside {
            get {
                return ResourceManager.GetString("acquisition_photos_outside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verzekeringsbewijs.
        /// </summary>
        public static string acquisition_photos_proofOfInsuranceTitle {
            get {
                return ResourceManager.GetString("acquisition_photos_proofOfInsuranceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechtsachter.
        /// </summary>
        public static string acquisition_photos_rightBackTitle {
            get {
                return ResourceManager.GetString("acquisition_photos_rightBackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechtsvooraan.
        /// </summary>
        public static string acquisition_photos_rightFrontTitle {
            get {
                return ResourceManager.GetString("acquisition_photos_rightFrontTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volg bovenstaande afbeelding en druk erop om de foto te uploaden..
        /// </summary>
        public static string acquisition_photos_text {
            get {
                return ResourceManager.GetString("acquisition_photos_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uw aanvraag werd succesvol verzonden!.
        /// </summary>
        public static string action_model_success {
            get {
                return ResourceManager.GetString("action_model_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doorgestuurde data van klant.
        /// </summary>
        public static string car_rental_body {
            get {
                return ResourceManager.GetString("car_rental_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vanaf.
        /// </summary>
        public static string car_rental_from {
            get {
                return ResourceManager.GetString("car_rental_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aanvraag voor het huren van een wagen door.
        /// </summary>
        public static string car_rental_heading {
            get {
                return ResourceManager.GetString("car_rental_heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inbegrepen in de prijs.
        /// </summary>
        public static string car_rental_included_in_price {
            get {
                return ResourceManager.GetString("car_rental_included_in_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuwe huur aanvraag autoverhuur door.
        /// </summary>
        public static string car_rental_subject_business {
            get {
                return ResourceManager.GetString("car_rental_subject_business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uw huur aanvraag werd succesvol verzonden!.
        /// </summary>
        public static string car_rental_subject_customer {
            get {
                return ResourceManager.GetString("car_rental_subject_customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dag(en).
        /// </summary>
        public static string car_rental_time_day {
            get {
                return ResourceManager.GetString("car_rental_time_day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week(en).
        /// </summary>
        public static string car_rental_time_week {
            get {
                return ResourceManager.GetString("car_rental_time_week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huurtermijn.
        /// </summary>
        public static string car_rental_timeperiod {
            get {
                return ResourceManager.GetString("car_rental_timeperiod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uw heeft een bericht ontvangen van.
        /// </summary>
        public static string contact_message {
            get {
                return ResourceManager.GetString("contact_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stuur een bericht.
        /// </summary>
        public static string contact_send_a_message {
            get {
                return ResourceManager.GetString("contact_send_a_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maand.
        /// </summary>
        public static string experience_month {
            get {
                return ResourceManager.GetString("experience_month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maanden.
        /// </summary>
        public static string experience_months {
            get {
                return ResourceManager.GetString("experience_months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen ervaring nodig..
        /// </summary>
        public static string experience_none {
            get {
                return ResourceManager.GetString("experience_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jaar.
        /// </summary>
        public static string experience_years {
            get {
                return ResourceManager.GetString("experience_years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle rechten voorbehouden..
        /// </summary>
        public static string general_allRightsReserved {
            get {
                return ResourceManager.GetString("general_allRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beantwoord.
        /// </summary>
        public static string general_answer {
            get {
                return ResourceManager.GetString("general_answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuleren.
        /// </summary>
        public static string general_cancel {
            get {
                return ResourceManager.GetString("general_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefoonnummer.
        /// </summary>
        public static string general_cellNumber {
            get {
                return ResourceManager.GetString("general_cellNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sluiten.
        /// </summary>
        public static string general_close {
            get {
                return ResourceManager.GetString("general_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltooid.
        /// </summary>
        public static string general_complete {
            get {
                return ResourceManager.GetString("general_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verzenden.
        /// </summary>
        public static string general_completeAction {
            get {
                return ResourceManager.GetString("general_completeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verder.
        /// </summary>
        public static string general_continue {
            get {
                return ResourceManager.GetString("general_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uw gegevens.
        /// </summary>
        public static string general_data {
            get {
                return ResourceManager.GetString("general_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aangemaakt op.
        /// </summary>
        public static string general_date_created {
            get {
                return ResourceManager.GetString("general_date_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dag.
        /// </summary>
        public static string general_day {
            get {
                return ResourceManager.GetString("general_day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mailadres.
        /// </summary>
        public static string general_email {
            get {
                return ResourceManager.GetString("general_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niets ingegeven.
        /// </summary>
        public static string general_empty_field {
            get {
                return ResourceManager.GetString("general_empty_field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probeer het later nog eens.
        /// </summary>
        public static string general_error_body {
            get {
                return ResourceManager.GetString("general_error_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is iets misgelopen.
        /// </summary>
        public static string general_error_header {
            get {
                return ResourceManager.GetString("general_error_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felix Groep.
        /// </summary>
        public static string general_felixGroup {
            get {
                return ResourceManager.GetString("general_felixGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voor- en achternaam.
        /// </summary>
        public static string general_first_lastname {
            get {
                return ResourceManager.GetString("general_first_lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voornaam.
        /// </summary>
        public static string general_firstname {
            get {
                return ResourceManager.GetString("general_firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam.
        /// </summary>
        public static string general_fullName {
            get {
                return ResourceManager.GetString("general_fullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terug.
        /// </summary>
        public static string general_goToPreviousPage {
            get {
                return ResourceManager.GetString("general_goToPreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string general_HomePage {
            get {
                return ResourceManager.GetString("general_HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achternaam.
        /// </summary>
        public static string general_lastname {
            get {
                return ResourceManager.GetString("general_lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uw aanvraag werd succesvol verzonden en wordt zo snel mogelijk behandeld..
        /// </summary>
        public static string general_mailClient_body {
            get {
                return ResourceManager.GetString("general_mailClient_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uw aanvraag werd succesvol verzonden.
        /// </summary>
        public static string general_mailClient_heading {
            get {
                return ResourceManager.GetString("general_mailClient_heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string general_modelName {
            get {
                return ResourceManager.GetString("general_modelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maand.
        /// </summary>
        public static string general_month {
            get {
                return ResourceManager.GetString("general_month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuws.
        /// </summary>
        public static string general_news {
            get {
                return ResourceManager.GetString("general_news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U bent succesvol ingeschreven op onze nieuwsbrief..
        /// </summary>
        public static string general_newsletterSuccess {
            get {
                return ResourceManager.GetString("general_newsletterSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overzicht.
        /// </summary>
        public static string general_overview {
            get {
                return ResourceManager.GetString("general_overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lees meer.
        /// </summary>
        public static string general_readmore {
            get {
                return ResourceManager.GetString("general_readmore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beste.
        /// </summary>
        public static string general_salutation {
            get {
                return ResourceManager.GetString("general_salutation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecteer uw optie.
        /// </summary>
        public static string general_selectOption {
            get {
                return ResourceManager.GetString("general_selectOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overslaan.
        /// </summary>
        public static string general_skip {
            get {
                return ResourceManager.GetString("general_skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succes!.
        /// </summary>
        public static string general_success {
            get {
                return ResourceManager.GetString("general_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to week.
        /// </summary>
        public static string general_week {
            get {
                return ResourceManager.GetString("general_week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uw bericht.
        /// </summary>
        public static string general_yourMessage {
            get {
                return ResourceManager.GetString("general_yourMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact formulier.
        /// </summary>
        public static string googlemapsContactForm_modal_title {
            get {
                return ResourceManager.GetString("googlemapsContactForm_modal_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bedankt voor uw sollicitatie!.
        /// </summary>
        public static string jobapplication_success {
            get {
                return ResourceManager.GetString("jobapplication_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stuurde u het volgende bericht.
        /// </summary>
        public static string mailContact_body {
            get {
                return ResourceManager.GetString("mailContact_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bericht van.
        /// </summary>
        public static string mailContact_heading {
            get {
                return ResourceManager.GetString("mailContact_heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is een nieuw bericht verstuurd in verband met een.
        /// </summary>
        public static string mailContact_newContactMessage1 {
            get {
                return ResourceManager.GetString("mailContact_newContactMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wagen van type.
        /// </summary>
        public static string mailContact_newContactMessage2 {
            get {
                return ResourceManager.GetString("mailContact_newContactMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to klik.
        /// </summary>
        public static string mailContact_newMessageContinued1 {
            get {
                return ResourceManager.GetString("mailContact_newMessageContinued1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klik.
        /// </summary>
        public static string mailContact_newMessageContinued1_withUppercase {
            get {
                return ResourceManager.GetString("mailContact_newMessageContinued1_withUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hier.
        /// </summary>
        public static string mailContact_newMessageContinued2 {
            get {
                return ResourceManager.GetString("mailContact_newMessageContinued2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to voor alle details van de wagen..
        /// </summary>
        public static string mailContact_newMessageContinued3 {
            get {
                return ResourceManager.GetString("mailContact_newMessageContinued3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informatie offerte aanvraag.
        /// </summary>
        public static string mailOfferte_body {
            get {
                return ResourceManager.GetString("mailOfferte_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is een offerte aangevraagd door.
        /// </summary>
        public static string mailOfferte_heading {
            get {
                return ResourceManager.GetString("mailOfferte_heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We zorgen ervoor dat u spoedig antwoord krijgt..
        /// </summary>
        public static string mails_mailbody_acquisitionclient {
            get {
                return ResourceManager.GetString("mails_mailbody_acquisitionclient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uw overname is correct opgenomen.
        /// </summary>
        public static string mails_mailsubject_acquisitionclient {
            get {
                return ResourceManager.GetString("mails_mailsubject_acquisitionclient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informatie testrit aanvraag.
        /// </summary>
        public static string mailTestrit_body {
            get {
                return ResourceManager.GetString("mailTestrit_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is een testrit aangevraagd door.
        /// </summary>
        public static string mailTestrit_heading {
            get {
                return ResourceManager.GetString("mailTestrit_heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er liep iets fout bij het valideren van uw data..
        /// </summary>
        public static string modal_error {
            get {
                return ResourceManager.GetString("modal_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelieve uw data na te kijken en opnieuw in te sturen..
        /// </summary>
        public static string modal_error_check {
            get {
                return ResourceManager.GetString("modal_error_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er liep iets fout bij het aanvragen van uw huuraanvraag. Controleer de ingevoerde data &amp; probeer opnieuw..
        /// </summary>
        public static string notification_carrental_error_message {
            get {
                return ResourceManager.GetString("notification_carrental_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uw aanvraag voor het huren van een wagen werd succesvol verstuurd &amp; is momenteel in behandeling.
        /// </summary>
        public static string notification_carrental_succes_message {
            get {
                return ResourceManager.GetString("notification_carrental_succes_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is iets fout gelopen bij het verzenden van uw ingevoerde data. Wijzig uw data &amp; probeer het opnieuw..
        /// </summary>
        public static string notification_contact_error_message {
            get {
                return ResourceManager.GetString("notification_contact_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uw bericht werd succesvol doorgestuurd &amp; is momenteel in behandeling..
        /// </summary>
        public static string notification_contact_success_message {
            get {
                return ResourceManager.GetString("notification_contact_success_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oeps!.
        /// </summary>
        public static string notification_error_title {
            get {
                return ResourceManager.GetString("notification_error_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er liep iets fout bij het indienden van uw sollicitatie. Controleer de ingevoerde data &amp; probeer opnieuw..
        /// </summary>
        public static string notification_jobapplication_error_message {
            get {
                return ResourceManager.GetString("notification_jobapplication_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uw sollicitatie werd succesvol ingediend en is momenteel in behandeling..
        /// </summary>
        public static string notification_jobapplication_success_message {
            get {
                return ResourceManager.GetString("notification_jobapplication_success_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er liep iets fout bij het aanvragen van uw offerte. Controleer de ingevoerde data &amp; probeer opnieuw..
        /// </summary>
        public static string notification_quotation_error_message {
            get {
                return ResourceManager.GetString("notification_quotation_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uw offerte werd succesvol aangevraagd en is momenteel in behandeling. Gelieve uw mailbox in de gaten te houden..
        /// </summary>
        public static string notification_quotation_success_message {
            get {
                return ResourceManager.GetString("notification_quotation_success_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succes!.
        /// </summary>
        public static string notification_success_title {
            get {
                return ResourceManager.GetString("notification_success_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er liep iets fout bij het aanvragen van uw testrit. Controleer de ingevoerde data &amp; probeer opnieuw..
        /// </summary>
        public static string notification_testdrive_error_message {
            get {
                return ResourceManager.GetString("notification_testdrive_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uw testrit werd succesvol aangevraagd en is momenteel in behandeling..
        /// </summary>
        public static string notification_testdrive_success_message {
            get {
                return ResourceManager.GetString("notification_testdrive_success_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesloten.
        /// </summary>
        public static string openingsHours_closed {
            get {
                return ResourceManager.GetString("openingsHours_closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Openingsuren Receptie.
        /// </summary>
        public static string openingsHours_reception {
            get {
                return ResourceManager.GetString("openingsHours_reception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Openingsuren toonzaal.
        /// </summary>
        public static string openingsHours_showroom {
            get {
                return ResourceManager.GetString("openingsHours_showroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Openingsuren Werkplaats.
        /// </summary>
        public static string openingsHours_workplace {
            get {
                return ResourceManager.GetString("openingsHours_workplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makelaar: telefoon nummer.
        /// </summary>
        public static string overname_agent_cellphone {
            get {
                return ResourceManager.GetString("overname_agent_cellphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GSM-nummer makelaar.
        /// </summary>
        public static string overname_agent_cellphone_readable {
            get {
                return ResourceManager.GetString("overname_agent_cellphone_readable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makelaar: gemeente.
        /// </summary>
        public static string overname_agent_city {
            get {
                return ResourceManager.GetString("overname_agent_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gemeente makelaar.
        /// </summary>
        public static string overname_agent_city_readable {
            get {
                return ResourceManager.GetString("overname_agent_city_readable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makelaar: email.
        /// </summary>
        public static string overname_agent_email {
            get {
                return ResourceManager.GetString("overname_agent_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email makelaar.
        /// </summary>
        public static string overname_agent_email_readable {
            get {
                return ResourceManager.GetString("overname_agent_email_readable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makelaar: naam.
        /// </summary>
        public static string overname_agent_name {
            get {
                return ResourceManager.GetString("overname_agent_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam makelaar.
        /// </summary>
        public static string overname_agent_name_readable {
            get {
                return ResourceManager.GetString("overname_agent_name_readable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vul dit veld in..
        /// </summary>
        public static string overname_errormessage_agent_cellphone {
            get {
                return ResourceManager.GetString("overname_errormessage_agent_cellphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vul dit veld in..
        /// </summary>
        public static string overname_errormessage_agent_city {
            get {
                return ResourceManager.GetString("overname_errormessage_agent_city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vul dit veld in..
        /// </summary>
        public static string overname_errormessage_agent_email {
            get {
                return ResourceManager.GetString("overname_errormessage_agent_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vul dit veld in..
        /// </summary>
        public static string overname_errormessage_agent_name {
            get {
                return ResourceManager.GetString("overname_errormessage_agent_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelieve een chassisnummer in te vullen.
        /// </summary>
        public static string overname_errormessage_chassisnumber {
            get {
                return ResourceManager.GetString("overname_errormessage_chassisnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vul dit veld in..
        /// </summary>
        public static string overname_errormessage_email {
            get {
                return ResourceManager.GetString("overname_errormessage_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vul dit veld in..
        /// </summary>
        public static string overname_errormessage_first_lastname {
            get {
                return ResourceManager.GetString("overname_errormessage_first_lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vul dit veld in..
        /// </summary>
        public static string overname_errormessage_firstname {
            get {
                return ResourceManager.GetString("overname_errormessage_firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vul dit veld in..
        /// </summary>
        public static string overname_errormessage_gsm {
            get {
                return ResourceManager.GetString("overname_errormessage_gsm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het minimum aantal foto&apos;s is: .
        /// </summary>
        public static string overname_errormessage_hoeveelheid_schade_fotos {
            get {
                return ResourceManager.GetString("overname_errormessage_hoeveelheid_schade_fotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kies een optie..
        /// </summary>
        public static string overname_errormessage_insurance {
            get {
                return ResourceManager.GetString("overname_errormessage_insurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vul dit veld in..
        /// </summary>
        public static string overname_errormessage_lastname {
            get {
                return ResourceManager.GetString("overname_errormessage_lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vul dit veld in..
        /// </summary>
        public static string overname_errormessage_licenseplate {
            get {
                return ResourceManager.GetString("overname_errormessage_licenseplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kies een optie..
        /// </summary>
        public static string overname_errormessage_manual {
            get {
                return ResourceManager.GetString("overname_errormessage_manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kies een optie..
        /// </summary>
        public static string overname_errormessage_wheelstate {
            get {
                return ResourceManager.GetString("overname_errormessage_wheelstate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dit veld is leeggelaten..
        /// </summary>
        public static string overname_field_is_empty_readable {
            get {
                return ResourceManager.GetString("overname_field_is_empty_readable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verzekeraar.
        /// </summary>
        public static string overname_insurance {
            get {
                return ResourceManager.GetString("overname_insurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verzekeraar.
        /// </summary>
        public static string overname_insurance_readable {
            get {
                return ResourceManager.GetString("overname_insurance_readable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schade is verzekerd.
        /// </summary>
        public static string overname_is_insured {
            get {
                return ResourceManager.GetString("overname_is_insured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achterbumper.
        /// </summary>
        public static string overname_scheme_bumper_back {
            get {
                return ResourceManager.GetString("overname_scheme_bumper_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voorbumper.
        /// </summary>
        public static string overname_scheme_bumper_front {
            get {
                return ResourceManager.GetString("overname_scheme_bumper_front", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten laste van de klant.
        /// </summary>
        public static string overname_scheme_client_cost {
            get {
                return ResourceManager.GetString("overname_scheme_client_cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kosten.
        /// </summary>
        public static string overname_scheme_costs {
            get {
                return ResourceManager.GetString("overname_scheme_costs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deuk.
        /// </summary>
        public static string overname_scheme_damage {
            get {
                return ResourceManager.GetString("overname_scheme_damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zwaar beschadigd.
        /// </summary>
        public static string overname_scheme_damage_heavy {
            get {
                return ResourceManager.GetString("overname_scheme_damage_heavy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lichte schade.
        /// </summary>
        public static string overname_scheme_damage_light {
            get {
                return ResourceManager.GetString("overname_scheme_damage_light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hagel of stormschade.
        /// </summary>
        public static string overname_scheme_hail_damage {
            get {
                return ResourceManager.GetString("overname_scheme_hail_damage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motorkap.
        /// </summary>
        public static string overname_scheme_hood {
            get {
                return ResourceManager.GetString("overname_scheme_hood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interieur.
        /// </summary>
        public static string overname_scheme_inside {
            get {
                return ResourceManager.GetString("overname_scheme_inside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linker achterdeur.
        /// </summary>
        public static string overname_scheme_left_door_back {
            get {
                return ResourceManager.GetString("overname_scheme_left_door_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linker voordeur.
        /// </summary>
        public static string overname_scheme_left_door_front {
            get {
                return ResourceManager.GetString("overname_scheme_left_door_front", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linker achterwiel.
        /// </summary>
        public static string overname_scheme_left_wheel_back {
            get {
                return ResourceManager.GetString("overname_scheme_left_wheel_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linker achtervleugel.
        /// </summary>
        public static string overname_scheme_left_wheel_cap_back {
            get {
                return ResourceManager.GetString("overname_scheme_left_wheel_cap_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linker voorvleugel.
        /// </summary>
        public static string overname_scheme_left_wheel_cap_front {
            get {
                return ResourceManager.GetString("overname_scheme_left_wheel_cap_front", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linker voorwiel.
        /// </summary>
        public static string overname_scheme_left_wheel_front {
            get {
                return ResourceManager.GetString("overname_scheme_left_wheel_front", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localisatie.
        /// </summary>
        public static string overname_scheme_local {
            get {
                return ResourceManager.GetString("overname_scheme_local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lakschade.
        /// </summary>
        public static string overname_scheme_marks {
            get {
                return ResourceManager.GetString("overname_scheme_marks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heeft u nog opmerkingen over dit geselecteerd onderdeel.
        /// </summary>
        public static string overname_scheme_remarks {
            get {
                return ResourceManager.GetString("overname_scheme_remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechter achterdeur.
        /// </summary>
        public static string overname_scheme_right_door_back {
            get {
                return ResourceManager.GetString("overname_scheme_right_door_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechter voordeur.
        /// </summary>
        public static string overname_scheme_right_door_front {
            get {
                return ResourceManager.GetString("overname_scheme_right_door_front", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechter achterwiel.
        /// </summary>
        public static string overname_scheme_right_wheel_back {
            get {
                return ResourceManager.GetString("overname_scheme_right_wheel_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechter achtervleugel.
        /// </summary>
        public static string overname_scheme_right_wheel_cap_back {
            get {
                return ResourceManager.GetString("overname_scheme_right_wheel_cap_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechter voorvleugel.
        /// </summary>
        public static string overname_scheme_right_wheel_cap_front {
            get {
                return ResourceManager.GetString("overname_scheme_right_wheel_cap_front", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechter voorwiel.
        /// </summary>
        public static string overname_scheme_right_wheel_front {
            get {
                return ResourceManager.GetString("overname_scheme_right_wheel_front", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dak.
        /// </summary>
        public static string overname_scheme_roof {
            get {
                return ResourceManager.GetString("overname_scheme_roof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duid alle beschadigde onderdelen aan.
        /// </summary>
        public static string overname_scheme_title {
            get {
                return ResourceManager.GetString("overname_scheme_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kofferdeksel.
        /// </summary>
        public static string overname_scheme_trunk {
            get {
                return ResourceManager.GetString("overname_scheme_trunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onderkant.
        /// </summary>
        public static string overname_scheme_underneath {
            get {
                return ResourceManager.GetString("overname_scheme_underneath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voorruit.
        /// </summary>
        public static string overname_scheme_windshield {
            get {
                return ResourceManager.GetString("overname_scheme_windshield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uw verzekering.
        /// </summary>
        public static string overname_your_insurance {
            get {
                return ResourceManager.GetString("overname_your_insurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overzicht van doorgestuurde informatie.
        /// </summary>
        public static string pdf_title {
            get {
                return ResourceManager.GetString("pdf_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waarom mensen ons kiezen.
        /// </summary>
        public static string reviews_header {
            get {
                return ResourceManager.GetString("reviews_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tweedehands.
        /// </summary>
        public static string secondhand_simple {
            get {
                return ResourceManager.GetString("secondhand_simple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basis.
        /// </summary>
        public static string talenkennis_basic {
            get {
                return ResourceManager.GetString("talenkennis_basic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uitstekend.
        /// </summary>
        public static string talenkennis_excellent {
            get {
                return ResourceManager.GetString("talenkennis_excellent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goed.
        /// </summary>
        public static string talenkennis_good {
            get {
                return ResourceManager.GetString("talenkennis_good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niet van toepassing.
        /// </summary>
        public static string talenkennis_nvt {
            get {
                return ResourceManager.GetString("talenkennis_nvt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niet noodzakelijk.
        /// </summary>
        public static string talenkennis_unnecessary {
            get {
                return ResourceManager.GetString("talenkennis_unnecessary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeer goed.
        /// </summary>
        public static string talenkennis_verygood {
            get {
                return ResourceManager.GetString("talenkennis_verygood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TempIsCarRentalSuccess.
        /// </summary>
        public static string temp_is_carrental_success {
            get {
                return ResourceManager.GetString("temp_is_carrental_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TempIsContactSuccess.
        /// </summary>
        public static string temp_is_contact_success {
            get {
                return ResourceManager.GetString("temp_is_contact_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TempIsJobApplicationSuccess.
        /// </summary>
        public static string temp_is_jobapplication_success {
            get {
                return ResourceManager.GetString("temp_is_jobapplication_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TempIsQuotationSuccess.
        /// </summary>
        public static string temp_is_quotation_success {
            get {
                return ResourceManager.GetString("temp_is_quotation_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TempIsTestDriveSuccess.
        /// </summary>
        public static string temp_is_testdrive_success {
            get {
                return ResourceManager.GetString("temp_is_testdrive_success", resourceCulture);
            }
        }
    }
}
