// <auto-generated />
namespace FelixWebsite.Dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class UmbracoPageId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UmbracoPageId));
        
        string IMigrationMetadata.Id
        {
            get { return "202011171011257_UmbracoPageId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
