// <auto-generated />
namespace FelixWebsite.Dal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class IsAcquisitionFlowCompleted : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IsAcquisitionFlowCompleted));
        
        string IMigrationMetadata.Id
        {
            get { return "202003251228251_IsAcquisitionFlowCompleted"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
